/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "./common.js"
  
export declare namespace Transaction {
      
    export type TxnStruct = {sender: AddressLike, receiver: AddressLike, amount: BigNumberish, message: string, timestamp: BigNumberish}

    export type TxnStructOutput = [sender: string, receiver: string, amount: bigint, message: string, timestamp: bigint] & {sender: string, receiver: string, amount: bigint, message: string, timestamp: bigint }
  
    }

  export interface TransactionInterface extends Interface {
    getFunction(nameOrSignature: "getTransactions" | "sendTransaction" | "transactions"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'getTransactions', values?: undefined): string;
encodeFunctionData(functionFragment: 'sendTransaction', values: [AddressLike, BigNumberish, string]): string;
encodeFunctionData(functionFragment: 'transactions', values: [BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'getTransactions', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'sendTransaction', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transactions', data: BytesLike): Result;
  }

  

  export interface Transaction extends BaseContract {
    
    connect(runner?: ContractRunner | null): Transaction;
    waitForDeployment(): Promise<this>;

    interface: TransactionInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    getTransactions: TypedContractMethod<
      [],
      [Transaction.TxnStructOutput[]],
      'view'
    >
    

    
    sendTransaction: TypedContractMethod<
      [_receiver: AddressLike, _amount: BigNumberish, _message: string, ],
      [void],
      'nonpayable'
    >
    

    
    transactions: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[string, string, bigint, string, bigint] & {sender: string, receiver: string, amount: bigint, message: string, timestamp: bigint }],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'getTransactions'): TypedContractMethod<
      [],
      [Transaction.TxnStructOutput[]],
      'view'
    >;
getFunction(nameOrSignature: 'sendTransaction'): TypedContractMethod<
      [_receiver: AddressLike, _amount: BigNumberish, _message: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'transactions'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[string, string, bigint, string, bigint] & {sender: string, receiver: string, amount: bigint, message: string, timestamp: bigint }],
      'view'
    >;

    

    filters: {
      
    };
  }